apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ecommerce-app
  namespace: argocd   # must be argocd namespace
spec:
  project: default

  source:
    repoURL: https://github.com/GAO-abs/k8s-manifests-argocd-gitops.git
    targetRevision: HEAD
    path: ecommerce-app-chart   # folder in repo where manifests are

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true